version: '3'

services:
  rap-backend:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_SRV: ${DATABASE_SRV}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      DATABASE_AUTHENTICATION_DATABASE: ${DATABASE_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    ports:
      - 1337:1337
    volumes:
      - ./api:/app/rap-backend/api
      - ./config:/app/rap-backend/config
      - ./public:/app/rap-backend/public
      - ./extensions:/app/rap-backend/extensions
    depends_on:
      - rap-mongo
    restart: "no"

  rap-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
